"""add id field to price

Revision ID: 0ecc305bbd5d
Revises: e0a8538013d5
Create Date: 2024-03-12 18:12:29.607960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ecc305bbd5d"
down_revision: Union[str, None] = "e0a8538013d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "id")
    # ### end Alembic commands ###
