"""remove id field to price

Revision ID: 5757f5189df8
Revises: 0ecc305bbd5d
Create Date: 2024-03-13 16:41:56.422678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5757f5189df8"
down_revision: Union[str, None] = "0ecc305bbd5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
