"""fix issues with foreign key

Revision ID: a957d5e5205b
Revises: 215aa941f7b9
Create Date: 2024-03-14 09:37:13.620027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a957d5e5205b"
down_revision: Union[str, None] = "215aa941f7b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("matrix_logs", "matrix_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("matrix_logs", "matrix_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
