"""add type to matrix

Revision ID: cdd4d0ad495d
Revises: 0db370d842b5
Create Date: 2024-03-10 11:42:40.400684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdd4d0ad495d"
down_revision: Union[str, None] = "0db370d842b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

matrix_type_enum = postgresql.ENUM("BASE", "DISCOUNT", name="matrix_type_enum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    matrix_type_enum.create(op.get_bind())
    op.add_column("matrices", sa.Column("type", matrix_type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matrices", "type")
    matrix_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
