"""add cascade deletion

Revision ID: e0a8538013d5
Revises: 3c142d6c4af4
Create Date: 2024-03-11 15:15:31.161910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0a8538013d5"
down_revision: Union[str, None] = "3c142d6c4af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("categories_parent_id_fkey", "categories", type_="foreignkey")
    op.create_foreign_key(None, "categories", "categories", ["parent_id"], ["id"], ondelete="cascade")
    op.drop_constraint("locations_parent_id_fkey", "locations", type_="foreignkey")
    op.create_foreign_key(None, "locations", "locations", ["parent_id"], ["id"], ondelete="cascade")
    op.drop_constraint("prices_matrix_id_fkey", "prices", type_="foreignkey")
    op.drop_constraint("prices_location_id_fkey", "prices", type_="foreignkey")
    op.drop_constraint("prices_category_id_fkey", "prices", type_="foreignkey")
    op.create_foreign_key(None, "prices", "categories", ["category_id"], ["id"], ondelete="cascade")
    op.create_foreign_key(None, "prices", "matrices", ["matrix_id"], ["id"], ondelete="cascade")
    op.create_foreign_key(None, "prices", "locations", ["location_id"], ["id"], ondelete="cascade")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prices", type_="foreignkey")
    op.drop_constraint(None, "prices", type_="foreignkey")
    op.drop_constraint(None, "prices", type_="foreignkey")
    op.create_foreign_key("prices_category_id_fkey", "prices", "categories", ["category_id"], ["id"])
    op.create_foreign_key("prices_location_id_fkey", "prices", "locations", ["location_id"], ["id"])
    op.create_foreign_key("prices_matrix_id_fkey", "prices", "matrices", ["matrix_id"], ["id"])
    op.drop_constraint(None, "locations", type_="foreignkey")
    op.create_foreign_key("locations_parent_id_fkey", "locations", "locations", ["parent_id"], ["id"])
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.create_foreign_key("categories_parent_id_fkey", "categories", "categories", ["parent_id"], ["id"])
    # ### end Alembic commands ###
